name = "Wish Fulfillment: Simply Vanilla 1.19"
version = "1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4db3c84f3791618691998e2e9296245c74fc01147e094da7b5a981a120530481"

[versions]
fabric = "0.14.6"
minecraft = "1.19"

[options]
acceptable-game-versions = ["1.19", "1.19-Snapshot"]
