name = "Vanilla Tweaks Dark Mode"
filename = "Vanilla Tweaks_DarkMode.zip"
side = "client"

[option]
optional = true
default = true
description = "Implements Vanilla Tweaks' Dark Mode to Minecraft's GUI."

[download]
url = "https://www.dropbox.com/s/gt4nep2wkymyms2/VanillaTweaks_DarkMode.zip?dl=1"
hash-format = "sha256"
hash = "C7D0B75AAF40054BDCDEA7FC619EDA87FAAE60BD57CE151E769898900312B780"