name = "Vanilla Tweaks Wild Update"
filename = "Vanilla Tweaks_WildUpdate.zip"
side = "client"

[option]
optional = "true"
default = "true"
description = "Vanilla Tweaks is about tweaking parts of the vanilla game that we believe can be a little bit better. They're mostly subtle changes to improve the default game experience. The website includes a picker with which you can create your very own collection of tweaks to be included in your game. You pick and choose, we do the rest!"

[download]
url = "https://www.dropbox.com/s/dek2nyr0lm284ti/VanillaTweaks_WildUpdate.zip?dl=1"
hash-format = "sha256"
hash = "9EF2E5D391DC9B84C0C1DE5BFA784C95E5B57149BF87EEC451A828F42A880E59"