name = "Wish Fulillment: Origins"
author = "cassphodel"
version = "1.14"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "102c6699c37f075d4e796502548e2604f7080ba32c7c9597e5e13b0c72279452"

[versions]
fabric = "0.14.6"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4"]
