name = "Wish Fulfillment: Origins 2"
author = "cassphodel"
version = "2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8987dfe7569172826ae6137b7af6ae055251c8a4217bd808281776adddff00ad"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18.1", "1.18"]
