name = "Wish Fulfillment: Simply Vanilla 1.16"
author = "cassphodel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d04eadbe5c07c879061ae4c9c1d34141afcada78259ff1a6edf315ec560f028d"

[versions]
fabric = "0.14.6"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16"]
