name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcfe158e6919e4853df2ef3af0f3430f1c2b141eb7da11b982e75b4a23f25caa"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
