name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80b794564a60d76209b65566de08ae084488591d1ad606c6fa6f47eeaa594cfd"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
