name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f83d399d88fc64eb2078cdc6d3a61a536affdb7f1f4e9e985b758bdc7bada853"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
