name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "be36441f08120861adf30398d45aa4e672ce72d594bd0c3c98f429d7cf61fbc1"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
