name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb9d704655cbe066e1b6ed5317ff2f367a11df3b3215efe2f8ee7ff0ff62d218"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
