name = "Simply Vanilla 1.18"
author = "cassphodel"
version = "1.18.2v8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9e28964f3542a57e221e5e3a6d35ba2385c7c9644258a32d5486accb49e4e697"

[versions]
fabric = "0.14.6"
minecraft = "1.18.2"
