name = "Anarchistic Conveniences"
author = "cassphodel"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e66d52312949fbefba2e81e5201d795e283fe3b04548a47e8c3ec4f2323ca6a6"

[versions]
fabric = "0.14.8"
minecraft = "1.16.5"
