name = "Wish Fulfillment: Generations"
author = "cassphodel"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee5a287aeb1ef89be0811cda2b478c968fe1c8298fd386c040ebe637d64de374"

[versions]
fabric = "0.14.6"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4", "1.16.3"]
