name = "Wish Fulfillment: Generations"
author = "cassphodel"
version = "1.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4140709d1be18f5087879246faac20c0f9cc5bfefb4b7753c877f6095131e1b4"

[versions]
fabric = "0.14.6"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.5", "1.16.4", "1.16.3"]
