name = "Crucial 2"
author = "Vazkii"
version = "1.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54c589dfcc5444ac05a41c051be136c3b9106c9b5bc3442ca1d85b6ddfa5a5fd"

[versions]
forge = "36.2.33"
minecraft = "1.16.5"
